# This is a basic workflow to help you get started with Actions

name: Unit Tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v2.0.0
        with:
          distribution: 'zulu' 
          java-version: '16'
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Run JUnit Testsuite
        
      # Load junit console starter
      - name: Download junit console starter
        run: curl -O https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.0-M1/junit-platform-console-standalone-1.8.0-M1.jar

      # Compile and Run Tests
      - name: Compile and Run JUnit Tests
        run: | 
          ls
          mkdir compiled
          javac -d compiled -cp junit-platform-console-standalone-1.8.0-M1.jar ./src/**/*.java
          java -jar junit-platform-console-standalone-1.8.0-M1.jar --class-path compiled --scan-class-path
